import type { Metadata } from "next";
import { Source_Serif_4 } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { AuroraBackground } from "@/components/ui/aurora-background";
import NavigationBar from "@/components/NavigationBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const sourceSerif4 = Source_Serif_4({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={sourceSerif4.className}>
      <body className="">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div id="/"></div>
          <header className="sticky top-0 z-40">
            <NavigationBar />
          </header>

          <AuroraBackground className="h-auto min-h-screen">
            {children}
          </AuroraBackground>
        </ThemeProvider>
      </body>
    </html>
  );
}
